apiVersion: v1
kind: Pod 
metadata:
  name: pizza-pod 
spec:
  containers:
    - name: pizza-container
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      resources:
        limits:
          cpu: "500m"
          memory: "256Mi"
        requests:
          cpu: "250m"
          memory: "128Mi"
      envFrom:
        - configMapRef:
            name: pizza-config
        - secretRef:
            name: pizza-secret